version: "3"

services:
  web:
    build : .
    ports:
      - "5000:5000"
    links:
      - NutrAspectdb

  NutrAspectdb:
    build: "../db"
    ports:
      - "27017:27017"
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_CLUSTER_NAME: db